const data = [
  {
    id: "standard_01",
    image: "/img/sub_page/standard_img1.jpg",
    title: "바꾸 일렉트릭 스트로베리 믹스",
    price: 12900,
  },
  {
    id: "standard_02",
    image: "/img/sub_page/standard_img2.jpg",
    title: "바꾸 스탠다드 파머스 마켓",
    price: 12900,
  },
  {
    id: "standard_03",
    image: "/img/sub_page/standard_img3.jpg",
    title: "바꾸 스탠다드 리버베드",
    price: 11900,
  },
  {
    id: "standard_04",
    image: "/img/sub_page/standard_img4.jpg",
    title: "바꾸 스탠다드 플라워베드",
    price: 12900,
  },
  {
    id: "standard_05",
    image: "/img/sub_page/standard_img5.jpg",
    title: "바꾸 스탠다드 우드블럭 프로랄 블랙",
    price: 13500,
  },
  {
    id: "standard_06",
    image: "/img/sub_page/standard_img6.jpg",
    title: "바꾸 스탠다드 데드스톡 해피 믹스",
    price: 13500,
  },
  {
    id: "standard_07",
    image: "/img/sub_page/standard_img7.jpg",
    title: "바꾸 스탠다드 데드스톡 오렌지 글러브",
    price: 13500,
  },
  {
    id: "standard_08",
    image: "/img/sub_page/standard_img8.jpg",
    title: "바꾸 스탠다드 데드스톡 카모 플라워",
    price: 11900,
  },
  {
    id: "standard_09",
    image: "/img/sub_page/standard_img9.jpg",
    title: "바꾸 스탠다드 데드스톡 럭스",
    price: 12900,
  },
  {
    id: "standard_10",
    image: "/img/sub_page/standard_img10.jpg",
    title: "바꾸 스탠다드 데드스톡 우드랜드",
    price: 11900,
  },
  {
    id: "standard_11",
    image: "/img/sub_page/standard_img11.jpg",
    title: "바꾸 스탠다드 팝 플로랄",
    price: 13500,
  },
  {
    id: "standard_12",
    image: "/img/sub_page/standard_img12.jpg",
    title: "바꾸 스탠다드 와일드 데이지",
    price: 12900,
  },
  {
    id: "standard_13",
    image: "/img/sub_page/standard_img13.jpg",
    title: "바꾸 와일드 데이지",
    price: 12900,
  },
  {
    id: "standard_14",
    image: "/img/sub_page/standard_img14.jpg",
    title: "바꾸 스탠다드 라임 로즈",
    price: 12900,
  },
  {
    id: "standard_15",
    image: "/img/sub_page/standard_img15.jpg",
    title: "바꾸 스탠다드 메달리온 플로랄",
    price: 13500,
  },
  {
    id: "standard_16",
    image: "/img/sub_page/standard_img16.jpg",
    title: "바꾸 스탠다드 레이디버그 리프",
    price: 13500,
  },
  {
    id: "standard_17",
    image: "/img/sub_page/standard_img17.jpg",
    title: "바꾸 스탠다드 스네일 프렌즈",
    price: 11900,
  },
  {
    id: "standard_18",
    image: "/img/sub_page/standard_img18.jpg",
    title: "바꾸 스탠다드 엘리펀트 블러썸",
    price: 12900,
  },
  {
    id: "standard_19",
    image: "/img/sub_page/standard_img19.jpg",
    title: "바꾸 스탠다드 빅 체크 멀티",
    price: 13500,
  },
  {
    id: "standard_20",
    image: "/img/sub_page/standard_img20.jpg",
    title: "바꾸 스탠다드 70s 마드라스",
    price: 11900,
  },
  {
    id: "standard_21",
    image: "/img/sub_page/standard_img21.jpg",
    title: "바꾸 스탠다드 아카이브 그레이프 프루트",
    price: 11900,
  },
  {
    id: "standard_22",
    image: "/img/sub_page/standard_img22.jpg",
    title: "바꾸 스탠다드 플러피 캣",
    price: 12900,
  },
  {
    id: "standard_23",
    image: "/img/sub_page/standard_img23.jpg",
    title: "바꾸 스탠다드 바나나",
    price: 13500,
  },
  {
    id: "standard_24",
    image: "/img/sub_page/standard_img24.jpg",
    title: "바꾸 스탠다드 라즈베리 해피",
    price: 12900,
  },
  {
    id: "standard_25",
    image: "/img/sub_page/standard_img25.jpg",
    title: "바꾸 스탠다드 옐로우 해피",
    price: 12900,
  },
  {
    id: "standard_26",
    image: "/img/sub_page/standard_img26.jpg",
    title: "바꾸 스탠다드 블랙 칼리코 플로랄",
    price: 11900,
  },
  {
    id: "standard_27",
    image: "/img/sub_page/standard_img27.jpg",
    title: "바꾸 스탠다드 하프 스퀘어",
    price: 11900,
  },
  {
    id: "standard_28",
    image: "/img/sub_page/standard_img28.jpg",
    title: "바꾸 스탠다드 푸들",
    price: 12900,
  },
  {
    id: "standard_29",
    image: "/img/sub_page/standard_img29.jpg",
    title: "바꾸 스탠다드 리브라",
    price: 13500,
  },
  {
    id: "standard_30",
    image: "/img/sub_page/standard_img30.jpg",
    title: "바꾸 스탠다드 세지타우러스",
    price: 12900,
  },
  {
    id: "standard_31",
    image: "/img/sub_page/standard_img31.jpg",
    title: "바꾸 스탠다드 타우러스",
    price: 12900,
  },
  {
    id: "standard_32",
    image: "/img/sub_page/standard_img32.jpg",
    title: "바꾸 스탠다드 퍼시몬 컬리지",
    price: 13500,
  },
];

export default data;
